# Generated by Django 3.2.6 on 2022-09-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0004_auto_20220927_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passExp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
