# Generated by Django 3.2.6 on 2022-09-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0005_auto_20220927_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passExp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passNo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
    ]
