# Generated by Django 3.2.6 on 2021-11-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0005_auto_20211116_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
