# Generated by Django 3.2.9 on 2021-11-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0007_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.department'),
        ),
    ]
