# Generated by Django 3.2.6 on 2022-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0007_auto_20220927_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateTimeField(null=True),
        ),
    ]
