# Generated by Django 3.2.9 on 2021-11-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0008_alter_designation_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customAdmin.designation'),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_designation_name', to='customAdmin.employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.employee')),
            ],
        ),
    ]
