# Generated by Django 3.2.6 on 2022-10-12 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0008_alter_employee_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
