# Generated by Django 3.2.6 on 2022-10-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0009_alter_employee_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
