# Generated by Django 3.2.6 on 2021-11-30 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0009_auto_20211120_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaydate', models.DateField(default=datetime.date.today)),
                ('timein', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('timeout', models.TimeField(blank=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customAdmin.employee')),
            ],
        ),
    ]
