# Generated by Django 3.2.6 on 2022-10-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0011_primaryemergencycontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
