# Generated by Django 3.2.6 on 2021-11-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0012_auto_20211130_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='timein',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='timeout',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='todaydate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
