# Generated by Django 3.2.6 on 2021-11-30 17:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0013_auto_20211201_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='timein',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='timeout',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='todaydate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
