# Generated by Django 3.2.6 on 2021-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0014_auto_20211201_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='timein',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='timeout',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='todaydate',
            field=models.DateField(),
        ),
    ]
