# Generated by Django 3.2.9 on 2022-11-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0014_alter_primaryemergencycontacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
