# Generated by Django 3.2.6 on 2021-11-30 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0015_auto_20211201_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='todaydate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
