# Generated by Django 3.2.6 on 2021-11-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0016_alter_employeeattendance_todaydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_id', to='customAdmin.employee'),
        ),
    ]
