# Generated by Django 3.2.9 on 2022-11-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0018_employeeattendance_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.IntegerField(blank=True, max_length=250)),
                ('daily_rate', models.IntegerField(blank=True, max_length=250)),
                ('gross_salary', models.IntegerField(blank=True, max_length=250)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customAdmin.employee')),
            ],
        ),
    ]
