# Generated by Django 3.2.9 on 2022-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0019_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='pag_ibig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='philhealth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='sss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='daily_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='gross_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
