# Generated by Django 3.2.9 on 2022-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0021_employeesalary_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='hours',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
