# Generated by Django 4.1 on 2022-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0021_employeesalary_net_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('confirm_password', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
