# Generated by Django 3.2.9 on 2022-11-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0022_auto_20221121_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='lateMin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
