# Generated by Django 3.2.9 on 2022-11-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0023_employeeattendance_latemin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='lateMin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
