# Generated by Django 4.1 on 2022-11-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0023_alter_accountofficer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountofficer',
            name='confirm_password',
        ),
    ]
