# Generated by Django 4.1 on 2022-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0024_remove_accountofficer_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountofficer',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
