# Generated by Django 3.2.9 on 2022-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0024_alter_employeeattendance_latemin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.TimeField(blank=True, null=True)),
                ('timeout', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
