# Generated by Django 3.2.9 on 2022-11-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0023_alter_accountofficer_email'),
        ('customAdmin', '0026_employeeschedule_status'),
    ]

    operations = [
    ]
