# Generated by Django 4.1 on 2022-11-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0025_alter_accountofficer_password'),
        ('customAdmin', '0026_employeeschedule_status'),
    ]

    operations = [
    ]
