# Generated by Django 3.2.9 on 2022-11-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0027_merge_20221123_1618'),
        ('customAdmin', '0027_merge_20221123_1629'),
    ]

    operations = [
    ]
