# Generated by Django 3.2.6 on 2022-11-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0027_merge_20221124_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='timein',
            new_name='schedin',
        ),
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='timeout',
            new_name='schedout',
        ),
    ]
