# Generated by Django 3.2.6 on 2022-11-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0028_auto_20221124_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='schedin',
            new_name='timein',
        ),
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='schedout',
            new_name='timeout',
        ),
    ]
