# Generated by Django 3.2.6 on 2022-11-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0029_auto_20221124_1744'),
        ('customAdmin', '0029_auto_20221124_2123'),
    ]

    operations = [
    ]
